language: r

r:
  -oldrel
  -release
  -devel

warnings_are_errors: true

os:
  - linux
  
compiler:
  - gcc -fsanitize=address

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then apt-get install mesa-common-dev freeglut3 freeglut3-dev libglew1.5 libglew1.5-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev; fi


env:
  
  global: RGL_USE_NULL=TRUE

