language: r

warnings_are_errors: true

os:
  - linux

sudo: required

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then apt-get install mesa-common-dev freeglut3 freeglut3-dev libglew1.5 libglew1.5-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev; fi

jobs:

  - compiler: 
      - gcc
  - RVERSION=devel _R_SAN_=TRUE _R_CHECK_FULL_=TRUE
  

env:
  
  global: RGL_USE_NULL=TRUE

