language: r
warnings_are_errors: true
sudo: required
before_install:
  - sudo apt-get install mesa-common-dev
  - sudo apt-get install freeglut3 freeglut3-dev libglew1.5 libglew1.5-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev
env:
  global: RGL_USE_NULL=TRUE
  
