language: r

r:
  -oldrel
  -release
  -devel

warnings_are_errors: true

#sudo: required

os:
  - linux
  
compiler:
  - gcc 
  env:

        - INSTALL_GCC6_FROM_PPA=1

        - LIBCXX_BUILD=1 LIBCXX_SANITIZER="Undefined;Address"

        - ENABLE_SANITIZER=1

        - EXTRA_FLAGS="-g -O2 -fno-omit-frame-pointer -fsanitize=undefined,address -fno-sanitize-recover=all"
  

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then apt-get install mesa-common-dev freeglut3 freeglut3-dev libglew1.5 libglew1.5-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev; fi

env:

  global: RGL_USE_NULL=TRUE

#matrix:
#  include:
#  - compiler: gcc
#      env:
#        - INSTALL_GCC6_FROM_PPA=1
#        - COMPILER=g++-6 C_COMPILER=gcc-6  BUILD_TYPE=Debug
#        - ENABLE_SANITIZER=1
#        - EXTRA_FLAGS="-fno-omit-frame-pointer -g -O2 -fsanitize=undefined,address -fuse-ld=gold"
